language: go
dist: trusty

go:
  - 1.8
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE suluvir;'
  - make build
  - ./server u
