version = "0.0.1"

[auth]
registration_disabled = false

[development]
development_mode = true

[upload]
path = "uploads"
relative = true

[web]
port = 8080
hostname = "localhost"

[database]
dialect = "sqlite3"
connection_string = "suluvir.db"
