version = "0.0.1"

[auth]
registration_disabled = false

[development]
development_mode = true

[upload]
path = "uploads"
relative = true

[web]
port = 8080
hostname = "localhost"

[database]
dialect = "sqlite3"
connection_string = "suluvir.db"

[quota]
songs = 500
space = "500M"

[mail]
server_name = ""
port = 0
user_name = ""
password = ""
email = "noreply@example.org"
