version = "0.0.1"

[auth]
registration_disabled = false

[oauth]
    [oauth.google]
    enabled = false
    client_id = ""

[development]
development_mode = true

[upload]
path = "uploads"
relative = true

[web]
# this is the port the application listens on
port = 8080
# this is the port the application is visible to the outside world. When using a reverse proxy, set it's value
# to the bind port of the proxy
outside_port = 8080
hostname = "localhost"
# this sets the instance to secure mode, in which the session cookie is only set for ssl connections, links are all
# prefixed with `https` instead of `http` and so on...
secure = false

[database]
dialect = "mysql"
connection_string = "root:@/suluvir?charset=utf8&parseTime=True&loc=Local"

[quota]
songs = 500
space = "500M"

[mail]
server_name = ""
port = 0
user_name = ""
password = ""
email = "noreply@example.org"
